#!/usr/bin/env bash
# installs nginx on a remote server with its configuration

sudo apt-get -y update
sudo apt-get -y install nginx ufw  # Installing ufw package
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start

