#!/usr/bin/env bash
# Customizing a 404-error_page

# Updating Packages before performing installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/aminebk99 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "this page not found 404" | sudo tee /var/www/html/404.html
# Custom HTTP response header
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
# Testing configurations for syntax errors
sudo nginx -t

# restart nginx after implementing changes
sudo service nginx restart
